version: 1
pipelines:
  - name: MyPipeline
    stages:
      - name: Source
        actions:
          - name: SourceAction
            actionTypeId:
              category: Source
              owner: AWS
              provider: CodeCommit
              version: '1'
            configuration:
              RepositoryName: MyRepo
              BranchName: main
            outputArtifacts:
              - name: SourceOutput
      - name: Build
        actions:
          - name: BuildAction
            actionTypeId:
              category: Build
              owner: AWS
              provider: CodeBuild
              version: '1'
            inputArtifacts:
              - name: SourceOutput
            configuration:
              ProjectName: MyBuildProject
            outputArtifacts:
              - name: BuildOutput
      - name: Deploy
        actions:
          - name: DeployAction
            actionTypeId:
              category: Deploy
              owner: AWS
              provider: CloudFormation
              version: '1'
            inputArtifacts:
              - name: BuildOutput
            configuration:
              StackName: MyStack
